package analyzer

import "testing"

// tinyLimits reports on any comment at all, so a test only has to show that a
// skip rule kept the linter quiet.
func tinyLimits() Settings {
	return Settings{
		Defaults: KindSettings{MaxLines: ptr(1), MaxWidth: ptr(5)},
		Style:    noStyle(),
	}
}

func TestGeneratedFiles(t *testing.T) {
	generated := `// Code generated by protoc-gen-go. DO NOT EDIT.

package p

// This comment is far too wide to pass the limits used in this test.
func F() {}
`
	if got := runSrc(t, tinyLimits(), "p.pb.go", generated); len(got) != 0 {
		t.Errorf("generated file should be skipped, got %v", got)
	}

	s := tinyLimits()
	s.SkipGenerated = ptr(false)
	if got := runSrc(t, s, "p.pb.go", generated); len(got) == 0 {
		t.Error("skip-generated:false should let diagnostics through")
	}

	// the marker only counts above the package clause
	below := `package p

// Code generated by hand. DO NOT EDIT.
func F() {}
`
	if got := runSrc(t, tinyLimits(), "p.go", below); len(got) == 0 {
		t.Error("a marker below the package clause must not skip the file")
	}

	custom := tinyLimits()
	custom.GeneratedExtra = []string{`^// AUTOGENERATED`}
	autogen := `// AUTOGENERATED FILE

package p

// This comment is far too wide to pass the limits used in this test.
func F() {}
`
	if got := runSrc(t, custom, "p.go", autogen); len(got) != 0 {
		t.Errorf("generated-extra should skip the file, got %v", got)
	}
}

func TestSkipPaths(t *testing.T) {
	src := `package p

// This comment is far too wide to pass the limits used in this test.
func F() {}
`
	s := tinyLimits()
	s.SkipTests = ptr(true)
	if got := runSrc(t, s, "p_test.go", src); len(got) != 0 {
		t.Errorf("skip-tests should skip _test.go, got %v", got)
	}
	if got := runSrc(t, s, "p.go", src); len(got) == 0 {
		t.Error("skip-tests must not skip ordinary files")
	}

	s = tinyLimits()
	s.ExcludeFiles = []string{`/vendor/`, `\.gen\.go$`}
	for _, name := range []string{"/repo/vendor/x/p.go", "/repo/api.gen.go"} {
		if got := runSrc(t, s, name, src); len(got) != 0 {
			t.Errorf("exclude-files should skip %s, got %v", name, got)
		}
	}
	if got := runSrc(t, s, "/repo/api.go", src); len(got) == 0 {
		t.Error("exclude-files must not skip everything")
	}
}

func TestDirectivesExempt(t *testing.T) {
	src := `//go:build linux && !windows && (amd64 || arm64) && something_long

package p

//go:generate stringer -type=Kind -output kind_string.go -linecomment
//nolint:gochecknoglobals // the registry has to be global
//easyjson:json
func F() {}
`
	s := tinyLimits()
	s.DirectivePrefixesExtra = []string{"easyjson:"}
	if got := runSrc(t, s, "p.go", src); len(got) != 0 {
		t.Errorf("directives should be exempt, got %v", got)
	}

	s.IgnoreDirectives = ptr(false)
	if got := runSrc(t, s, "p.go", src); len(got) == 0 {
		t.Error("ignore-directives:false should measure directives too")
	}
}

func TestMixedDirectiveAndProse(t *testing.T) {
	// the directive line must not be counted, the prose lines must
	src := `package p

//go:noinline
// one
// two
func F() {}
`
	s := sizeOnly(KindExported, KindSettings{MaxLines: ptr(1)})
	assertDiags(t, runSrc(t, s, "p.go", src), []string{"5:1: exported comment is 2 lines long, max 1"})
}

func TestDisableDirectives(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want int
	}{
		{
			name: "disable file",
			src: `package p

//commentlen:disable-file

// This comment is far too wide to pass the limits used in this test.
func F() {}
`,
		},
		{
			name: "disable region",
			src: `package p

//commentlen:disable
// This comment is far too wide to pass the limits used in this test.
func F() {}

//commentlen:enable
`,
		},
		{
			name: "region reopens after enable",
			src: `package p

//commentlen:disable
// This comment is far too wide to pass the limits used in this test.
func F() {}
//commentlen:enable

// This one is measured and far too wide for the limits in this test.
func G() {}
`,
			want: 1, // only G's comment, and only for its width
		},
		{
			name: "ignore one declaration",
			src: `package p

//commentlen:ignore
// This comment is far too wide to pass the limits used in this test.
func F() {}

// Short
func G() {}
`,
			want: 1, // "Short" is still 8 columns wide
		},
		{
			name: "nolint covers the linter",
			src: `package p

//nolint:commentlen // measured elsewhere
// This comment is far too wide to pass the limits used in this test.
func F() {}
`,
		},
		{
			name: "nolint for another linter does not",
			src: `package p

//nolint:lll
// This comment is far too wide to pass the limits used in this test.
func F() {}
`,
			want: 1,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := runSrc(t, tinyLimits(), "p.go", tt.src)
			if len(got) != tt.want {
				t.Errorf("got %d diagnostics, want %d: %v", len(got), tt.want, got)
			}
		})
	}
}

func TestExcludePatterns(t *testing.T) {
	src := `package p

// SPDX-License-Identifier: Apache-2.0 with a very long trailing explanation
func F() {}

// This comment is far too wide to pass the limits used in this test.
func G() {}
`
	s := tinyLimits()
	s.ExcludePatterns = []string{`^SPDX-`}
	got := runSrc(t, s, "p.go", src)
	if len(got) != 1 {
		t.Fatalf("got %d diagnostics, want 1: %v", len(got), got)
	}
}
